### ISSUE TITLE
SetClimateSun/SunGlareTexture problem

### ISSUE THREAD

**Issue by GreamRipper** [c6-dev/ButcherPeteFOSE#2]
Hi,
Sorry to bother you again ...
I have tested SetClimateSunTexture
SetClimateSunGlareTexture
Set/GetClimateTraitNumeric
and it seems that only Set/GetClimateTraitNumeric is working...

I have tested with this script:

-----------------------------------------------------------------------

scn 0DWNewSunNewGlareTextureScript

begin gamemode

if gNewSunGlareActivation == 1 && gNewSunActivation == 1
      SetClimateSunTexture 0DWClimate "Sky\SunNew.dds"
      SetClimateSunGlareTexture 0DWClimate "Sky\SunGlareNew.dds"
      SetClimateSunTexture 0DWDCClimate "Sky\SunNew.dds"
      SetClimateSunGlareTexture 0DWDCClimate "Sky\SunGlareNew.dds"
      ;messageexalt 2 "Textures applied"
elseif gNewSunGlareActivation == 1 && gNewSunActivation == 0
      SetClimateSunTexture 0DWClimate "Sky\Sun.dds"
      SetClimateSunGlareTexture 0DWClimate "Sky\SunGlareNew.dds"
      SetClimateSunTexture 0DWDCClimate "Sky\Sun.dds"
      SetClimateSunGlareTexture 0DWDCClimate "Sky\SunGlareNew.dds"
      ;messageexalt 2 "New SunGlare applied"
elseif gNewSunActivation == 1 && gNewSunGlareActivation == 0
      SetClimateSunTexture 0DWClimate "Sky\SunNew.dds"
      SetClimateSunGlareTexture 0DWClimate "Sky\SunGlare.dds"
      SetClimateSunTexture 0DWDCClimate "Sky\SunNew.dds"
      SetClimateSunGlareTexture 0DWDCClimate "Sky\SunGlare.dds"
      ;messageexalt 2 "New Sun applied"
else
      SetClimateSunTexture 0DWClimate "Sky\Sun.dds"
      SetClimateSunGlareTexture 0DWClimate "Sky\SunGlare.dds"
      SetClimateSunTexture 0DWDCClimate "Sky\Sun.dds"
      SetClimateSunGlareTexture 0DWDCClimate "Sky\SunGlare.dds"
     ;messageexalt 2 "Original Textures Restored"
endif

;startquest 0DWForceForceWeatherQuest ; used to reload current weather

end

---------------------------------------------------------------

No effect in game, even after saving/reloading save with changes applied. Restarted the whole game from the very beginning and still does not work.
I am aware that new textures can only apply after game restart or save reload, I even checked archiveinvalidation invalidated was running ... nope, does not work
I also removed Sun/SunGlare texture path from Both climate templates in Dynamic Weather ESM and from my esp, thinking it could mismatch with new function but still does not work.
Checked loops access with messageexalt like for stopsoundalt and it shows message, meaning it goes through ...

The new functions are recognized though and compile fine in GECK ... my question : does FO3 engine built support string related functions?
Still have to test Set/GetClimateTraitNumeric at night but menu message reports correct change when modifying settings (0/1/2/3 for moons)....It does not use strings as arguments...

Hope you could help when available.

Regards

**Comment by GreamRipper** [comment]
Tested Set/GetClimateTraitNumeric at night and besides game settings changing when using both functions it does not affect moons in game.  Applied/saved settings in new game/new save and no moon change so far. The only way i could enable/disable (Masser only) was changing climate template itself in GECK. Is this hardcoded, does engine takes over? can't make it work as intended

another strange behaviour is game only showing 1 moon (Masser) as if secunda has no coded texture path. Couldn't find secunda textures in game data neither... may be I should give up on moon texture changes from menu! 

Edit : was able to show secunda Moon ! simply by adding a new set of textures to sky folder and renaming masser_XXX.dds files to secunda_XXX.dds :)

**Comment by c6-dev** [comment]
I'll check, but in general I just ported the functions, if there are some differences in the climate system between games (or JIP had the same issues) there isn't much i can do. Function code itself is pretty much identical

**Comment by GreamRipper** [comment]
Ok, don't worry, you already did great job and helped me a lot already.
Your plugin is sort of FOSE extension right? ... then FOSE probably needs to be recoded or updated to support such texture path/string functions.
I believe, some particular settings are hardcoded in executable (Texture paths, texture sizes, game settings (like iMasserSize, fSecundaSpeed ...) and engine takes over/ignore settings eventhough we can physically modify those settings ( SetNumericGameSetting has same problem/behaviour)
I can for example modify masser size, speed, z offset with menu interaction and appropriate script but it does not modify game behaviour even after a backup/restart (globals to backup/restore settings at every start/load).
Secunda moon is the best example : i just had to add textures in sky forlder and it made secunda appear in game after restart : it is hardcoded in exe no? looks like...
Would an injector be able to alter those settings? I mean, a special dll version of your plugin i can inject with simple injector (gameowner for example)

For now, these new functions are useless, you should probably remove them from ButcherPete.dll to avoid complains ; ) SetWorldSpaceClimate would certainly behave in the same way...Can you try with MoveToFade when you have time, I can test and give you feedback.

Many Thxs


    Le mercredi 8 janvier 2025 à 11:54:05 UTC+1, c6 ***@***.***> a écrit :  
 
 


I'll check, but in general I just ported the functions, if there are some differences in the climate system between games (or JIP had the same issues) there isn't much i can do

**Comment by c6-dev** [comment]
There is one more we missed - [RefreshCurrentClimate](https://geckwiki.com/index.php?title=RefreshCurrentClimate). I'm pretty sure it should fix the issues you are having. Will get it ported over

**Comment by c6-dev** [comment]
added Get/Set/RefreshCurrentClimate, at least these steps in console seem to work now:

1. `GetCurrentClimate` (returned WastelandClimate)
2. `SetClimateTraitNumeric WastelandClimate 5 0` (disable moons)
3. `RefreshCurrentClimate` - the moon disappears

You can try yourself with this dll
[ButcherPete.zip](https://github.com/user-attachments/files/18361401/ButcherPete.zip)

**Comment by GreamRipper** [comment]
Man ! You are awesome !!!  Indeed we (I) missed RefreshCurrentClimate ... It works great for Sun/SunGlare using SetClimateSun/SunGlareTexture new functions 
It works ok with moons and make them appear/desappear ... only one little problem remaining though.... it seems that something is inverted : disabling Masser actually disables Secunda and other way round. I checked from my side 
and script is ok : 

scn 0DWMoonsScript

begin gamemode

if gMasserActivation == 1 && gSecundaActivation == 1
	SetClimateTraitNumeric 0DWClimate 5 3
	SetClimateTraitNumeric 0DWDCClimate 5 3
	RefreshCurrentClimate
elseif gMasserActivation == 1 && gSecundaActivation == 0
	SetClimateTraitNumeric 0DWClimate 5 1
	SetClimateTraitNumeric 0DWDCClimate 5 1
	RefreshCurrentClimate
elseif gMasserActivation == 0 && gSecundaActivation == 1 
	SetClimateTraitNumeric 0DWClimate 5 2
	SetClimateTraitNumeric 0DWDCClimate 5 2
	RefreshCurrentClimate
elseif gMasserActivation == 0 && gSecundaActivation == 0
	SetClimateTraitNumeric 0DWClimate 5 0
	SetClimateTraitNumeric 0DWDCClimate 5 0
	RefreshCurrentClimate
endif
set gClimateCurrentMoonsConfig to GetClimateTraitNumeric 0DWClimate 5
stopquest 0DWMoonsQuest

end

Can you check from you side, it might be a problem with SetClimateTraitNumeric
Climate Numeric Trait IDs :
5	Moons (0 - None, 1 - Masser, 2 - Secunda, 3 - Both)

Vanilla game climate templates only refer to Masser (secunda disabled ) and Sky folder texture linked to masser  textures. This means that engine is set up properly as it shows up Masser.

You did awesome work ! I was about to give up and remove Sun/SunGlare/Moons scripts from my mod.... 
You take us to Next Level FO3 mods with such functions... thank you again

**Comment by c6-dev** [comment]
Oh, that's probably just a documentation error then. Thanks for testing

**Comment by GreamRipper** [comment]
You're very welcome! if you need a hand for testing, just ask and i'll help ; )
